site_name: DinoDB Documentation
site_description: Modern macOS DynamoDB client application
site_author: DinoDB Team
site_url: https://dinodb.app/docs

# Build to the docs directory for GitHub Pages
site_dir: ../docs

repo_name: vegasq/dinodbapp
repo_url: https://github.com/vegasq/dinodbapp
edit_uri: edit/main/docs/

theme:
  name: ivory

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Account Management: user-guide/account-management.md
    - Table Operations: user-guide/table-operations.md
    - Query Builder: user-guide/query-builder.md
    - Monitoring & Metrics: user-guide/monitoring.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vegasq/dinodbapp

# Copy additional directories
docs_dir: docs
use_directory_urls: true
